#! /usr/bin/env bash

if [ ! -r s-league ]
  then wget http://www.sleague.com/fixtures-results/fixtures/s-league
fi

sed "s/data_header/mata_header/" s-league | 
  grep -E -A7 "data[ alternate]?" |
    sed '/links/d;/div/d;/ul/d;s/<div>//;s/[ ]class="long"//g;s/<[\/]*li>//g' |
      tr '\r\n' ' ' | 
        sed 's/ -- /\n/g;' |
          sed 's/Venue  /\n/;/DATE/d'
